version: "3.9"

services:
  app:
    image: ${DOCKER_IMAGE:-ghcr.io/n07n0w/sandoria-sandbox:latest}
    container_name: sandbox-app
    restart: unless-stopped
    env_file:
      - .env
      - .env.version
    ports:
      - "3001:3000"
